Refix compile error:
```
Error: expected argument #1 to 'Mel::CronTask#to_json' to be IO,
not JSON::Builder
```

This reverts commit 937ab1cb69a7359c9811274aba25398d08b0e2fa.