Fix compile error in Crystal v1.8
```

Which expanded to:

 > 18 |   **job_args
 > 19 | ) : String?
 > 20 |   job = new(**job_args)
                ^--
Error: no overload matches 'CollectJobsJob.new' with type

Overloads are:
 - CollectJobsJob.new(pull : ::JSON::PullParser)
 - CollectJobsJob.new(*, __pull_for_json_serializable pull : ::JSON::PullParser)
```

This is likely due to <https://github.com/crystal-lang/crystal/pull/16147>.